"""Narrative significance signals — derive routing/frequency hints from
turn state.

Used by:
- ``image_coordinator`` to decide image generation frequency
- ``orchestrator`` to pick the narrator tier (standard / premium / opening)

## Architecture

The tiered narrator routing has two phases (see ``Docs/Roadmap/tiered_narrator.md``):

**Phase B — deterministic standard-veto.** Marks turns we *know* are mundane
without needing brain judgment. Combat narration, inventory shuffling,
currency-only transactions are all routine paths that should default to the
cheap narrator. The brain can still override Phase B's veto, but only with
an explicit ``"climactic"`` significance call (boss death blow, PC death
mid-combat, etc.) — ``"notable"`` is not enough to break a Phase B veto.

**Phase C — brain-driven premium-promote.** When Phase B doesn't veto,
the brain's ``narrative_significance`` classification decides. ``"notable"``
or ``"climactic"`` → premium; ``"routine"`` → standard.

This split respects the fact that Phase B has perfect knowledge of certain
mundane categories (you cannot have a "climactic inventory check") while the
brain has better judgment for the open-ended notable/climactic distinction
in dialogue, exploration, and dramatic combat moments.
"""

from __future__ import annotations

from typing import Iterable, Optional

from .effects import EffectType


# Effects that indicate a scene change for image-generation frequency.
# Note: this is separate from narrator-tier selection. Used by
# image_coordinator to decide whether to draw an image, NOT by the
# narrator tier selector.
_SCENE_CHANGE_EFFECT_TYPES = frozenset({
    EffectType.ADD_NPC,         # New NPC introduced
    EffectType.START_COMBAT,    # Combat begins
})


def is_scene_change(proposed_effects: Iterable) -> bool:
    """Detect if the current turn represents a scene change.

    Used by ``image_coordinator`` for image-frequency decisions. Returns
    True if a new NPC was added or combat started in this turn.

    NOT used by the narrator tier selector — that's brain-driven via
    Phase C significance.
    """
    if not proposed_effects:
        return False
    for effect in proposed_effects:
        effect_type = getattr(effect, "effect_type", None)
        if effect_type in _SCENE_CHANGE_EFFECT_TYPES:
            return True
    return False


def select_narrator_tier(
    *,
    is_opening: bool = False,
    definitely_standard: bool = False,
    significance: Optional[str] = None,
    force_tier: Optional[str] = None,
) -> str:
    """Pick the narrator tier for the current turn.

    Returns one of: ``"opening"``, ``"premium"``, ``"standard"``.

    Resolution order (first match wins):

    1. ``force_tier`` if provided (FORCE_NARRATOR_TIER env override).
    2. ``is_opening`` → ``"opening"``. Session-opener narrator. Doesn't
       go through the brain — the opener is generated by a synthetic
       action prefix the orchestrator detects without classification.
    3. **Phase B veto** — ``definitely_standard=True`` forces ``"standard"``
       UNLESS the brain explicitly classified the turn as ``"climactic"``.
       This handles the "boss's killing blow is in combat (Phase B says
       standard) but is still climactic" case.
    4. **Phase C** — brain says ``"notable"`` or ``"climactic"`` → premium.
    5. Default → ``"standard"``.

    Args:
        is_opening: True if the turn is the session opener.
        definitely_standard: True if Phase B knows this is a mundane path
            (combat narration, inventory action, currency-only transaction,
            etc.). Acts as a veto over Phase C unless the brain says climactic.
        significance: Brain-emitted classification — one of ``"routine"``,
            ``"notable"``, ``"climactic"``. ``None`` is treated as routine.
        force_tier: If set, returned verbatim — bypasses all logic.
    """
    if force_tier:
        return force_tier

    if is_opening:
        return "opening"

    # Phase B veto: known mundane paths default to standard. Only an
    # explicit "climactic" classification from the brain can override —
    # this preserves moments like the boss's final blow even though
    # they happen during ongoing combat.
    if definitely_standard:
        if significance == "climactic":
            return "premium"
        return "standard"

    # Phase C: brain-driven premium for notable/climactic moments.
    if significance in ("notable", "climactic"):
        return "premium"

    return "standard"
