"""Riva TTS (Text-to-Speech) wrapper.

Wraps NVIDIA Riva Magpie NIM for text-to-speech synthesis.
Supports streaming synthesis for low-latency sentence-by-sentence playback.
"""

from __future__ import annotations

import asyncio
import re
from typing import AsyncIterator

import numpy as np
import structlog

logger = structlog.get_logger()

# Audio constants
TTS_SAMPLE_RATE = 44100


def split_sentences(text: str) -> list[str]:
    """Split text into sentences for streaming TTS.

    Breaks on sentence-ending punctuation followed by whitespace.
    """
    sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if s.strip()]
    return sentences


class RivaTTS:
    """NVIDIA Riva Magpie TTS via gRPC.

    Synthesizes text to audio (int16 PCM arrays). Supports streaming
    sentence-by-sentence synthesis for low-latency playback.
    """

    def __init__(
        self,
        server_url: str = "localhost:50052",
        voice: str = "Magpie-Multilingual.EN-US.Aria",
    ):
        import riva.client

        auth = riva.client.Auth(uri=server_url, use_ssl=False)
        self.service = riva.client.SpeechSynthesisService(auth)
        self._riva = riva.client
        self.voice = voice
        self.sample_rate = TTS_SAMPLE_RATE
        logger.info("riva_tts_initialized", server=server_url, voice=voice)

    def synthesize(self, text: str) -> np.ndarray:
        """Synthesize text to a single audio array.

        Returns:
            numpy int16 array of audio samples at 44.1kHz.
        """
        responses = self.service.synthesize_online(
            [text],
            voice_name=self.voice,
            language_code="en-US",
            sample_rate_hz=self.sample_rate,
            encoding=self._riva.AudioEncoding.LINEAR_PCM,
        )
        chunks = []
        for resp in responses:
            chunk = np.frombuffer(resp.audio, dtype=np.int16)
            if len(chunk) > 0:
                chunks.append(chunk)

        if chunks:
            return np.concatenate(chunks)
        return np.array([], dtype=np.int16)

    def synthesize_stream(self, text: str):
        """Yield audio chunks as they're generated by Riva.

        Splits text into sentences and streams each. Yields numpy int16 arrays.
        """
        sentences = split_sentences(text)
        if not sentences:
            return

        responses = self.service.synthesize_online(
            sentences,
            voice_name=self.voice,
            language_code="en-US",
            sample_rate_hz=self.sample_rate,
            encoding=self._riva.AudioEncoding.LINEAR_PCM,
        )
        for resp in responses:
            chunk = np.frombuffer(resp.audio, dtype=np.int16)
            if len(chunk) > 0:
                yield chunk

    async def synthesize_async(self, text: str) -> np.ndarray:
        """Async wrapper around synchronous synthesize."""
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, self.synthesize, text)

    async def synthesize_stream_async(self, text: str) -> AsyncIterator[np.ndarray]:
        """Async generator that yields audio chunks.

        Runs the synchronous Riva gRPC call in an executor to avoid
        blocking the event loop.
        """
        loop = asyncio.get_event_loop()
        # Collect chunks in executor, yield them one by one
        chunks = await loop.run_in_executor(
            None, lambda: list(self.synthesize_stream(text))
        )
        for chunk in chunks:
            yield chunk


class TTSSentenceQueue:
    """Manages a queue of sentences to be synthesized.

    Buffers narrative tokens into complete sentences, then queues them
    for TTS synthesis. Used by VoiceFrontend to stream narration.
    """

    def __init__(self, tts: RivaTTS):
        self.tts = tts
        self._buffer: str = ""
        self._sentence_queue: asyncio.Queue[str | None] = asyncio.Queue()
        self._audio_queue: asyncio.Queue[np.ndarray | None] = asyncio.Queue()
        self._synth_task: asyncio.Task | None = None

    def add_token(self, token: str) -> None:
        """Add a narrative token. Flushes complete sentences to the queue."""
        self._buffer += token
        self._flush_sentences()

    def flush_remaining(self) -> None:
        """Flush any remaining buffered text as a final sentence."""
        if self._buffer.strip():
            self._sentence_queue.put_nowait(self._buffer.strip())
            self._buffer = ""
        self._sentence_queue.put_nowait(None)  # Signal done

    def _flush_sentences(self) -> None:
        """Extract complete sentences from buffer and queue them."""
        while True:
            match = re.search(r"[.!?]\s+", self._buffer)
            if match:
                sentence = self._buffer[: match.end()].strip()
                if sentence:
                    self._sentence_queue.put_nowait(sentence)
                self._buffer = self._buffer[match.end() :]
            else:
                break

    async def start_synthesis(self) -> None:
        """Start background synthesis task. Reads sentences, produces audio."""
        self._synth_task = asyncio.create_task(self._synthesis_loop())

    async def _synthesis_loop(self) -> None:
        """Background loop: pull sentences, synthesize, push audio chunks."""
        while True:
            sentence = await self._sentence_queue.get()
            if sentence is None:
                self._audio_queue.put_nowait(None)
                break

            try:
                audio = await self.tts.synthesize_async(sentence)
                if len(audio) > 0:
                    self._audio_queue.put_nowait(audio)
            except Exception as e:
                logger.warning("tts_synthesis_failed", error=str(e))

    async def get_audio_chunks(self) -> AsyncIterator[np.ndarray]:
        """Yield synthesized audio chunks as they become available."""
        while True:
            chunk = await self._audio_queue.get()
            if chunk is None:
                break
            yield chunk

    def reset(self) -> None:
        """Reset state for a new turn."""
        self._buffer = ""
        # Drain queues
        while not self._sentence_queue.empty():
            try:
                self._sentence_queue.get_nowait()
            except asyncio.QueueEmpty:
                break
        while not self._audio_queue.empty():
            try:
                self._audio_queue.get_nowait()
            except asyncio.QueueEmpty:
                break
        if self._synth_task and not self._synth_task.done():
            self._synth_task.cancel()
        self._synth_task = None
